name: Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: Run tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        xcodebuild \
          -project ArtificeLens.xcodeproj \
          -scheme ArtificeLens \
          -sdk macosx \
          CODE_SIGNING_ALLOWED=NO \
          test
